#!/bin/bash

base_dir="100-files"

for dir in "$base_dir"/*; do
  rm -rf "$dir/clean.sh"
  echo "Removed clean.sh from $dir"
  rm -rf "$dir/Komondor"
  echo "Removed Komondor from $dir"
  rm -rf "$dir/step3"
  echo "Removed step3 from $dir"
  rm -rf "$dir/step1/x-y_output"
  echo "Removed step3 from $dir"
  rm "$dir/step1/step1.sh"
  echo "Removed step1.sh from $dir"
  rm "$dir/step1/Wlan.java"
  echo "Removed Wlan.java from $dir"
  rm "$dir/step1/x-y.java"
  echo "Removed x-y.java from $dir"
  rm -rf "$dir/step2/v0.4"
  echo "Removed v0.4 from $dir"
  rm "$dir/step2/1.c"
  echo "Removed 1.c from $dir"
  rm "$dir/step2/a.out"
  echo "Removed a.out from $dir"
  rm "$dir/step2/input.txt"
  echo "Removed input.txt from $dir"

  rm "$dir/step2/input_nodes_copy_deployment_000.csv"
  echo "Removed input_nodes_copy_deployment_000.csv from $dir"
  rm "$dir/step2/step2.sh"
  echo "Removed step2.sh from $dir"
  rm "$dir/step2/points.sh"
  echo "Removed points.sh from $dir"
  rm "$dir/step2/oriz.py"
  echo "Removed oriz.py from $dir"

  rm "$dir/step4/1.sh"
  echo "Removed 1.sh from $dir"
  rm "$dir/step4/gbu.sh"
  echo "Removed gbu.sh from $dir"
  rm "$dir/step4/max.sh"
  echo "Removed min.sh from $dir"
  rm "$dir/step4/min.sh"
  echo "Removed max.sh from $dir"
  rm "$dir/step4/rename.sh"
  echo "Removed rename.sh from $dir"
  rm "$dir/step4/saigo-no-steppu.sh"
  echo "Removed saigo-no-steppu.sh from $dir"
done

echo "Completed removal of all useless directories."
